import { LeaderboardPlayer } from "./types";

export const mockLeaderboardData: LeaderboardPlayer[] = [
  {
    id: "1",
    rank: 1,
    username: "BoxMaster2024",
    displayName: "Alex Johnson",
    avatar: "/avatars/alex.jpg",
    totalScore: 15420,
    weeklyScore: 2340,
    monthlyScore: 8920,
    boxesOpened: 89,
    winRate: 0.78,
    streak: 12,
    maxStreak: 25,
    level: "Diamond",
    levelProgress: 85,
    badges: ["High Roller", "Lucky Streak", "Box Collector", "Diamond Master"],
    lastActive: new Date("2024-01-15T14:30:00"),
    joinDate: new Date("2023-06-15"),
    totalSpent: 2450.50,
    totalWon: 3200.75,
    netProfit: 750.25,
    favoriteBox: "Mystery Gold",
    achievements: 15,
    referrals: 8,
    status: "active",
    isVerified: true,
    country: "US",
    timezone: "EST",
  },
  {
    id: "2",
    rank: 2,
    username: "LuckyBoxer",
    displayName: "Sarah Chen",
    avatar: "/avatars/sarah.jpg",
    totalScore: 14280,
    weeklyScore: 1890,
    monthlyScore: 7650,
    boxesOpened: 76,
    winRate: 0.72,
    streak: 8,
    maxStreak: 18,
    level: "Diamond",
    levelProgress: 72,
    badges: ["Box Collector", "Consistent Player", "Lucky Streak"],
    lastActive: new Date("2024-01-15T12:15:00"),
    joinDate: new Date("2023-08-22"),
    totalSpent: 1890.25,
    totalWon: 2100.50,
    netProfit: 210.25,
    favoriteBox: "Lucky Silver",
    achievements: 12,
    referrals: 5,
    status: "active",
    isVerified: true,
    country: "CA",
    timezone: "PST",
  },
  {
    id: "3",
    rank: 3,
    username: "BoxHunter",
    displayName: "Mike Rodriguez",
    avatar: "/avatars/mike.jpg",
    totalScore: 12850,
    weeklyScore: 1650,
    monthlyScore: 6890,
    boxesOpened: 92,
    winRate: 0.68,
    streak: 5,
    maxStreak: 12,
    level: "Gold",
    levelProgress: 45,
    badges: ["Box Hunter", "Rising Star", "Volume Player"],
    lastActive: new Date("2024-01-15T09:45:00"),
    joinDate: new Date("2023-09-10"),
    totalSpent: 3200.75,
    totalWon: 2800.25,
    netProfit: -400.50,
    favoriteBox: "Hunter's Choice",
    achievements: 8,
    referrals: 3,
    status: "active",
    isVerified: false,
    country: "MX",
    timezone: "CST",
  },
  {
    id: "4",
    rank: 4,
    username: "MysteryBoxPro",
    displayName: "Emma Wilson",
    avatar: "/avatars/emma.jpg",
    totalScore: 11560,
    weeklyScore: 1420,
    monthlyScore: 5420,
    boxesOpened: 68,
    winRate: 0.75,
    streak: 15,
    maxStreak: 22,
    level: "Gold",
    levelProgress: 38,
    badges: ["Mystery Master", "Lucky Streak", "High Win Rate"],
    lastActive: new Date("2024-01-14T18:20:00"),
    joinDate: new Date("2023-07-05"),
    totalSpent: 1650.00,
    totalWon: 1950.75,
    netProfit: 300.75,
    favoriteBox: "Mystery Pro",
    achievements: 10,
    referrals: 6,
    status: "active",
    isVerified: true,
    country: "UK",
    timezone: "GMT",
  },
  {
    id: "5",
    rank: 5,
    username: "BoxWizard",
    displayName: "David Kim",
    avatar: "/avatars/david.jpg",
    totalScore: 10890,
    weeklyScore: 980,
    monthlyScore: 4200,
    boxesOpened: 81,
    winRate: 0.65,
    streak: 3,
    maxStreak: 9,
    level: "Gold",
    levelProgress: 25,
    badges: ["Box Wizard", "Steady Player", "Consistent"],
    lastActive: new Date("2024-01-14T16:10:00"),
    joinDate: new Date("2023-10-12"),
    totalSpent: 2100.50,
    totalWon: 1800.25,
    netProfit: -300.25,
    favoriteBox: "Wizard's Box",
    achievements: 7,
    referrals: 2,
    status: "active",
    isVerified: false,
    country: "KR",
    timezone: "KST",
  },
  {
    id: "6",
    rank: 6,
    username: "LuckyCharm",
    displayName: "Lisa Park",
    avatar: "/avatars/lisa.jpg",
    totalScore: 9870,
    weeklyScore: 1230,
    monthlyScore: 3890,
    boxesOpened: 54,
    winRate: 0.82,
    streak: 7,
    maxStreak: 14,
    level: "Silver",
    levelProgress: 65,
    badges: ["Lucky Charm", "High Win Rate", "Efficient Player"],
    lastActive: new Date("2024-01-14T14:30:00"),
    joinDate: new Date("2023-11-08"),
    totalSpent: 890.25,
    totalWon: 1200.50,
    netProfit: 310.25,
    favoriteBox: "Lucky Charm",
    achievements: 6,
    referrals: 4,
    status: "active",
    isVerified: true,
    country: "JP",
    timezone: "JST",
  },
  {
    id: "7",
    rank: 7,
    username: "BoxExplorer",
    displayName: "James Brown",
    avatar: "/avatars/james.jpg",
    totalScore: 9230,
    weeklyScore: 890,
    monthlyScore: 3450,
    boxesOpened: 73,
    winRate: 0.58,
    streak: 2,
    maxStreak: 7,
    level: "Silver",
    levelProgress: 42,
    badges: ["Explorer", "Box Collector", "Adventurer"],
    lastActive: new Date("2024-01-14T11:45:00"),
    joinDate: new Date("2023-12-01"),
    totalSpent: 1500.75,
    totalWon: 1200.25,
    netProfit: -300.50,
    favoriteBox: "Explorer's Pack",
    achievements: 5,
    referrals: 1,
    status: "active",
    isVerified: false,
    country: "AU",
    timezone: "AEST",
  },
  {
    id: "8",
    rank: 8,
    username: "MysterySeeker",
    displayName: "Anna Taylor",
    avatar: "/avatars/anna.jpg",
    totalScore: 8760,
    weeklyScore: 1100,
    monthlyScore: 3200,
    boxesOpened: 45,
    winRate: 0.71,
    streak: 4,
    maxStreak: 11,
    level: "Silver",
    levelProgress: 28,
    badges: ["Mystery Seeker", "Rising Star", "Focused Player"],
    lastActive: new Date("2024-01-14T08:20:00"),
    joinDate: new Date("2023-11-20"),
    totalSpent: 750.50,
    totalWon: 950.25,
    netProfit: 199.75,
    favoriteBox: "Seeker's Mystery",
    achievements: 4,
    referrals: 3,
    status: "active",
    isVerified: false,
    country: "DE",
    timezone: "CET",
  },
  {
    id: "9",
    rank: 9,
    username: "BoxChampion",
    displayName: "Robert Lee",
    avatar: "/avatars/robert.jpg",
    totalScore: 8120,
    weeklyScore: 750,
    monthlyScore: 2800,
    boxesOpened: 62,
    winRate: 0.63,
    streak: 1,
    maxStreak: 5,
    level: "Bronze",
    levelProgress: 75,
    badges: ["Champion", "Steady Player", "Persistent"],
    lastActive: new Date("2024-01-13T20:15:00"),
    joinDate: new Date("2023-12-15"),
    totalSpent: 1200.00,
    totalWon: 950.75,
    netProfit: -249.25,
    favoriteBox: "Champion's Choice",
    achievements: 3,
    referrals: 2,
    status: "active",
    isVerified: false,
    country: "BR",
    timezone: "BRT",
  },
  {
    id: "10",
    rank: 10,
    username: "LuckyBox",
    displayName: "Maria Garcia",
    avatar: "/avatars/maria.jpg",
    totalScore: 7890,
    weeklyScore: 650,
    monthlyScore: 2100,
    boxesOpened: 38,
    winRate: 0.69,
    streak: 6,
    maxStreak: 8,
    level: "Bronze",
    levelProgress: 55,
    badges: ["Lucky Box", "New Player", "Quick Learner"],
    lastActive: new Date("2024-01-13T17:30:00"),
    joinDate: new Date("2024-01-02"),
    totalSpent: 450.25,
    totalWon: 520.75,
    netProfit: 70.50,
    favoriteBox: "Newcomer's Luck",
    achievements: 2,
    referrals: 1,
    status: "active",
    isVerified: false,
    country: "ES",
    timezone: "CET",
  },
];
