export const boxContent = [
  {
    title: "Audemars Piguet",
    tag: "MOST WANTED",
    star: 5,
    image: "/box/box-item/box2.webp",
    price: "$25,000",
    percentage: "% 0.002",
    color: "purple",
    href: "",
  },
  {
    title: "Louis Vuitton Bumbag",
    tag: "MOST WANTED",
    star: 5,
    image: "/box/box-item/box6.webp",
    price: "£2,120",
    percentage: "% 0.010",
    color: "purple",
    href: "",
  },
  {
    title: "Designer Cardigan",
    tag: "MOST WANTED",
    star: 5,
    image: "/box/box-item/box4.webp",
    price: "$1,200",
    percentage: "% 0.050",
    color: "purple",
    href: "",
  },
  {
    title: "Premium Sneakers",
    tag: "MOST WANTED",
    star: 5,
    image: "/box/box-item/box8.webp",
    price: "$800",
    percentage: "% 0.100",
    color: "purple",
    href: "",
  },
  {
    title: "Designer Sunglasses",
    tag: "MOST WANTED",
    star: 5,
    image: "/box/box-item/box1.webp",
    price: "$500",
    percentage: "% 0.200",
    color: "purple",
    href: "",
  },
  {
    title: "Diamond Ring",
    tag: "WANTED",
    star: 4,
    image: "/box/box-item/box7.webp",
    price: "$2,500",
    percentage: "% 0.025",
    color: "red",
    href: "",
  },
  {
    title: "Louis Vuitton Shoes",
    tag: "WANTED",
    star: 4,
    image: "/box/box-item/box3.webp",
    price: "$1,800",
    percentage: "% 0.075",
    color: "red",
    href: "",
  },
  {
    title: "MacBook Pro M3",
    tag: "WANTED",
    star: 4,
    image: "/box/box-item/box5.webp",
    price: "$3,500",
    percentage: "% 0.015",
    color: "red",
    href: "",
  },
  {
    title: "Supreme Hoodie",
    tag: "WANTED",
    star: 4,
    image: "/box/box-item/box0.webp",
    price: "$300",
    percentage: "% 0.100",
    color: "red",
    href: "",
  },
  {
    title: "PlayStation 5 Pro",
    tag: "WANTED",
    star: 4,
    image: "/box/box-item/box8.webp",
    price: "$700",
    percentage: "% 0.050",
    color: "red",
    href: "",
  },
  {
    title: "iPhone 15 Pro Max",
    tag: "IN DEMAND",
    star: 3,
    image: "/box/box-item/box2.webp",
    price: "$1,200",
    percentage: "% 0.150",
    color: "gold",
    href: "",
  },
  {
    title: "iPad Pro",
    tag: "IN DEMAND",
    star: 3,
    image: "/box/box-item/box4.webp",
    price: "$800",
    percentage: "% 0.200",
    color: "gold",
    href: "",
  },
  {
    title: "Nintendo Switch OLED",
    tag: "IN DEMAND",
    star: 3,
    image: "/box/box-item/box6.webp",
    price: "$350",
    percentage: "% 0.200",
    color: "gold",
    href: "",
  },
  {
    title: "Jordan Sneakers",
    tag: "IN DEMAND",
    star: 3,
    image: "/box/box-item/box1.webp",
    price: "$200",
    percentage: "% 0.150",
    color: "gold",
    href: "",
  },
  {
    title: "Xbox Series X",
    tag: "IN DEMAND",
    star: 3,
    image: "/box/box-item/box7.webp",
    price: "$500",
    percentage: "% 0.100",
    color: "gold",
    href: "",
  },
  {
    title: "AirPods Pro",
    tag: "UNCOMMON",
    star: 2,
    image: "/box/box-item/box3.webp",
    price: "$250",
    percentage: "% 0.400",
    color: "green",
    href: "",
  },
  {
    title: "Gaming Headset",
    tag: "UNCOMMON",
    star: 2,
    image: "/box/box-item/box5.webp",
    price: "$200",
    percentage: "% 0.300",
    color: "green",
    href: "",
  },
  {
    title: "Designer Cap",
    tag: "UNCOMMON",
    star: 2,
    image: "/box/box-item/box0.webp",
    price: "$80",
    percentage: "% 0.300",
    color: "green",
    href: "",
  },
  {
    title: "iPhone 14",
    tag: "UNCOMMON",
    star: 2,
    image: "/box/box-item/box8.webp",
    price: "$900",
    percentage: "% 0.250",
    color: "green",
    href: "",
  },
  {
    title: "Smartwatch",
    tag: "UNCOMMON",
    star: 2,
    image: "/box/box-item/box2.webp",
    price: "$300",
    percentage: "% 0.350",
    color: "green",
    href: "",
  },
  {
    title: "Apple Watch",
    tag: "COMMON",
    star: 1,
    image: "/box/box-item/box4.webp",
    price: "$400",
    percentage: "% 0.300",
    color: "blue",
    href: "",
  },
  {
    title: "Controller",
    tag: "COMMON",
    star: 1,
    image: "/box/box-item/box6.webp",
    price: "$70",
    percentage: "% 0.500",
    color: "blue",
    href: "",
  },
  {
    title: "Basic T-Shirt",
    tag: "COMMON",
    star: 1,
    image: "/box/box-item/box1.webp",
    price: "$25",
    percentage: "% 0.500",
    color: "blue",
    href: "",
  },
  {
    title: "Wireless Earbuds",
    tag: "COMMON",
    star: 1,
    image: "/box/box-item/box7.webp",
    price: "$50",
    percentage: "% 0.450",
    color: "blue",
    href: "",
  },
  {
    title: "Phone Case",
    tag: "COMMON",
    star: 1,
    image: "/box/box-item/box3.webp",
    price: "$15",
    percentage: "% 0.600",
    color: "blue",
    href: "",
  },
];