export const boxContent = [
  {
    title: "Audemars Piguet",
    tag: "MOST WANTED",
    star: 5,
    image: "/audemars-piguet.png",
    price: "$25,000",
    percentage: "% 0.002",
    color: "purple",
    href: "",
  },
  {
    title: "Louis Vuitton Bumbag",
    tag: "MOST WANTED",
    star: 5,
    image: "/lv-bumbag.png",
    price: "£2,120",
    percentage: "% 0.010",
    color: "purple",
    href: "",
  },
  {
    title: "XXX",
    tag: "MOST WANTED",
    star: 5,
    image: "/cardigan.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "purple",
    href: "",
  },
  {
    title: "XXX",
    tag: "MOST WANTED",
    star: 5,
    image: "/shoes.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "purple",
    href: "",
  },
  {
    title: "XXX",
    tag: "MOST WANTED",
    star: 5,
    image: "/sunglasses.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "purple",
    href: "",
  },
  {
    title: "XXX",
    tag: "WANTED",
    star: 4,
    image: "/diamond-ring.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "red",
    href: "",
  },
  {
    title: "XXX",
    tag: "WANTED",
    star: 4,
    image: "/diamond-ring.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "red",
    href: "",
  },
  {
    title: "XXX",
    tag: "WANTED",
    star: 4,
    image: "/diamond-ring.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "red",
    href: "",
  },
  {
    title: "XXX",
    tag: "WANTED",
    star: 4,
    image: "/diamond-ring.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "red",
    href: "",
  },
  {
    title: "XXX",
    tag: "WANTED",
    star: 4,
    image: "/diamond-ring.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "red",
    href: "",
  },
  {
    title: "XXX",
    tag: "IN DEMAND",
    star: 3,
    image: "/lv-shoes.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "gold",
    href: "",
  },
  {
    title: "XXX",
    tag: "IN DEMAND",
    star: 3,
    image: "/lv-shoes.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "gold",
    href: "",
  },
  {
    title: "XXX",
    tag: "IN DEMAND",
    star: 3,
    image: "/lv-shoes.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "gold",
    href: "",
  },
  {
    title: "XXX",
    tag: "IN DEMAND",
    star: 3,
    image: "/lv-shoes.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "gold",
    href: "",
  },
  {
    title: "XXX",
    tag: "IN DEMAND",
    star: 3,
    image: "/lv-shoes.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "gold",
    href: "",
  },
  {
    title: "XXX",
    tag: "UNCOMMON",
    star: 2,
    image: "/iphone.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "green",
    href: "",
  },
  {
    title: "XXX",
    tag: "UNCOMMON",
    star: 2,
    image: "/iphone.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "green",
    href: "",
  },
  {
    title: "XXX",
    tag: "UNCOMMON",
    star: 2,
    image: "/iphone.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "green",
    href: "",
  },
  {
    title: "XXX",
    tag: "UNCOMMON",
    star: 2,
    image: "/iphone.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "green",
    href: "",
  },
  {
    title: "XXX",
    tag: "UNCOMMON",
    star: 2,
    image: "/iphone.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "green",
    href: "",
  },
  {
    title: "XXX",
    tag: "COMMON",
    star: 1,
    image: "/xbox.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "blue",
    href: "",
  },
  {
    title: "XXX",
    tag: "COMMON",
    star: 1,
    image: "/xbox.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "blue",
    href: "",
  },
  {
    title: "XXX",
    tag: "COMMON",
    star: 1,
    image: "/xbox.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "blue",
    href: "",
  },
  {
    title: "XXX",
    tag: "COMMON",
    star: 1,
    image: "/xbox.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "blue",
    href: "",
  },
  {
    title: "XXX",
    tag: "COMMON",
    star: 1,
    image: "/xbox.png",
    price: "$0,000",
    percentage: "% 0.000",
    color: "blue",
    href: "",
  },
];
